name: shop_up_now
services:
  postgresqldb_service:
    container_name: postgresdb_service_container
    environment:
      POSTGRES_DB: shop_up_now_db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres:16.2
    ports:
      - mode: ingress
        target: 5432
        published: "5432"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: volume
        target: /var/lib/postgresql/data
        volume: {}

  shop_up_now_service:
    build: ./
    container_name: shop_up_now_service_container
    depends_on:
      postgresqldb_service:
        condition: service_started
        required: true
    image: shop_up_now
    ports:
      - mode: ingress
        target: 8080
        published: "8080"
        protocol: tcp

networks:
  default:
    name: shop_up_now_default